import React from 'react'
import * as Ph from '@phosphor-icons/react'

type PhosphorIconName = string

const iconMap: Record<string, React.ComponentType<any>> = {
  'squares-four': Ph.SquaresFour,
  'calendar-blank': Ph.CalendarBlank,
  'calendar-check': Ph.CalendarCheck,
  'calendar-plus': Ph.CalendarPlus,
  'cash-register': Ph.CashRegister,
  'users': Ph.Users,
  'scissors': Ph.Scissors,
  'package': Ph.Package,
  'identification-badge': Ph.IdentificationBadge,
  'chart-line-up': Ph.ChartLineUp,
  'whatsapp-logo': Ph.WhatsappLogo,
  'gear-six': Ph.GearSix,
  'magnifying-glass': Ph.MagnifyingGlass,
  'bell': Ph.Bell,
  'caret-up-down': Ph.CaretUpDown,
  'arrow-left': Ph.ArrowLeft,
  'arrow-right': Ph.ArrowRight,
  'arrow-up-right': Ph.ArrowUpRight,
  'user-switch': Ph.UserSwitch,
  'sign-out': Ph.SignOut,
  'warning': Ph.Warning,
  'user-minus': Ph.UserMinus,
  'hand-coins': Ph.HandCoins,
  'trend-up': Ph.TrendUp,
  'trend-down': Ph.TrendDown,
  'plus': Ph.Plus,
  'x': Ph.X,
  'check': Ph.Check,
  'pencil': Ph.Pencil,
  'trash': Ph.Trash,
  'crown-simple': Ph.CrownSimple,
  'heart': Ph.Heart,
  'sparkle': Ph.Sparkle,
  'star': Ph.Star,
  'star-half': Ph.StarHalf,
  'chart-bar': Ph.ChartBar,
  'chart-pie': Ph.ChartPie,
  'download': Ph.Download,
  'upload': Ph.Upload,
  'image': Ph.Image,
  'camera': Ph.Camera,
  'phone': Ph.Phone,
  'envelope': Ph.Envelope,
  'lock': Ph.Lock,
  'eye': Ph.Eye,
  'eye-slash': Ph.EyeSlash,
  'user': Ph.User,
  'user-plus': Ph.UserPlus,
  'users-three': Ph.UsersThree,
  'money': Ph.Money,
  'credit-card': Ph.CreditCard,
  'receipt': Ph.Receipt,
  'invoice': Ph.Invoice,
  'currency-circle-dollar': Ph.CurrencyCircleDollar,
  'storefront': Ph.Storefront,
  'clock': Ph.Clock,
  'calendar': Ph.Calendar,
  'notepad': Ph.Notepad,
  'clipboard': Ph.Clipboard,
  'paint-brush': Ph.PaintBrush,
  'palette': Ph.Palette,
  'tag': Ph.Tag,
  'tag-chevron': Ph.TagChevron,
  'funnel': Ph.Funnel,
  'sliders': Ph.Sliders,
  'dots-three-vertical': Ph.DotsThreeVertical,
  'dots-three': Ph.DotsThree,
  'info': Ph.Info,
  'question': Ph.Question,
  'check-circle': Ph.CheckCircle,
  'x-circle': Ph.XCircle,
  'paper-plane': Ph.PaperPlane,
  'paperclip': Ph.Paperclip,
  'chats': Ph.Chats,
  'chat': Ph.Chat,
  'chat-text': Ph.ChatText,
  'smiley': Ph.Smiley,
  'printer': Ph.Printer,
  'share': Ph.Share,
  'link': Ph.Link,
  'copy': Ph.Copy,
  'file': Ph.File,
  'files': Ph.Files,
  'folder': Ph.Folder,
  'export': Ph.Export,
  'import': Ph.ArrowSquareIn,
  'database': Ph.Database,
  'shield': Ph.Shield,
  'key': Ph.Key,
  'fingerprint': Ph.Fingerprint,
  'barcode': Ph.Barcode,
  'qr-code': Ph.QrCode,
  'globe': Ph.Globe,
  'house': Ph.House,
  'map-pin': Ph.MapPin,
  'shopping-cart': Ph.ShoppingCart,
  'shopping-bag': Ph.ShoppingBag,
  'gift': Ph.Gift,
  'flower': Ph.Flower,
  'drop': Ph.Drop,
  'sun': Ph.Sun,
  'moon': Ph.Moon,
  'sparkles': Ph.Sparkle,
  'confetti': Ph.Confetti,
  'flag': Ph.Flag,
  'lightning': Ph.Lightning,
  'fire': Ph.Fire,
  'leaf': Ph.Leaf,
  'medal': Ph.Medal,
  'trophy': Ph.Trophy,
  'plus-circle': Ph.PlusCircle,
  'caret-right': Ph.CaretRight,
  'link-simple': Ph.LinkSimple,
  'clock-countdown': Ph.ClockCountdown,
  'sliders-horizontal': Ph.SlidersHorizontal,
  'identification-card': Ph.IdentificationCard,
  'checks': Ph.Checks,
  'arrow-down-left': Ph.ArrowDownLeft,
  'arrow-circle-down': Ph.ArrowCircleDown,
  'arrow-circle-up': Ph.ArrowCircleUp,
  'percent': Ph.Percent,
  'calendar-x': Ph.CalendarX,
  'lock-simple': Ph.LockSimple,
  'pencil-simple': Ph.PencilSimple,
  'arrows-clockwise': Ph.ArrowsClockwise,
  'warning-circle': Ph.WarningCircle,
  'upload-simple': Ph.UploadSimple,
  'repeat': Ph.Repeat,
}

interface IconProps {
  n: PhosphorIconName
  w?: 'fill' | 'bold' | 'thin' | 'light' | 'duotone'
  size?: number
  style?: React.CSSProperties
}

export function PhosphorIcon({ n, w, size = 18, style }: IconProps) {
  const Component = iconMap[n]
  if (!Component) return <span style={{ width: size, height: size, display: 'inline-block' }} />
  return <Component size={size} weight={w || 'regular'} style={{ flexShrink: 0, ...style }} />
}
